- name: Add block of lines to existing file 
  hosts: all
  tasks:
    - name: Add the block
      blockinfile:
        path: /tmp/file.txt
        block: |
          line vjhbjkh jh 1
          line jh jh 2

- name: Add block of lines to new file 
  hosts: all
  tasks:
    - name: Add the block
      blockinfile:
        create: yes
        path: /tmp/file1.txt
        block: |
          line1
          line2
