## Register variables is nothing but storing the output of a task in a variable for future reference
- name: Register variables
  hosts: all
  tasks:
    - name: Execute id command
      shell: id
      register: out

    - name: Print registered variable 
      debug:
        msg: "{{out.stdout}}"
